uid: 50000
gid: 0

airflowHome: /opt/airflow
executor: "KubernetesExecutor"

defaultAirflowRepository: apache/airflow
defaultAirflowTag: "2.9.2"
airflowVersion: "2.9.2"

postgresql:
  enabled: true

scheduler:
  securityContext:
    runAsUser: 50000
    fsGroup: 0
    runAsGroup: 0
  resources:
    limits:
     cpu: 1000m
     memory: 1Gi
    requests:
     cpu: 400m
     memory: 400Mi
  enabled: true
  waitForMigrations:
    enabled: true

workers:
  securityContext:
    runAsUser: 50000
    fsGroup: 0
    runAsGroup: 0
    
webserver:
  resources:
    limits:
     cpu: 800m
     memory: 1Gi
    requests:
     cpu: 400m
     memory: 500Mi
  enabled: true
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
  service:
    type: NodePort
  waitForMigrations:
    enabled: true

triggerer:
  enabled: true
  waitForMigrations:
    enabled: true

dags:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: local-storage
    accessMode: ReadWriteOnce
    existingClaim: pv-airflow
  gitSync:
    enabled: false

logs:
  persistence:
    enabled: true
    size: 100Gi
    storageClassName: local-storage
    existingClaim: pv-logs
